driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /sbin/init

provisioner:
  name: chef_zero
  data_path: test/shared

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      dockerfile: .KitchenDockerfile.ubuntu-16.04
  - name: debian-8.9
    driver_config:
      dockerfile: .KitchenDockerfile.debian-8.9
  #- name: centos-7.3
  #  run_list:
  #    - recipe[yum::default]

suites:
  - name: default
    run_list:
        - recipe[prometheus::default]
        - recipe[prometheus::alertmanager]
    attributes:
      prometheus:
        install_method: 'binary'
        alertmanager:
          install_method: 'binary'
